stages:
- build

build:windows:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  only:
  - develop  
  tags:
  - windows
  script:
  - ruby bin/openstudio_meta install_gems -e /c/server-export

build:mac:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  only:
  - develop  
  tags:
  - mac
  script:
  - export RUBYLIB=/Applications/OpenStudio-2.3.0/Ruby/
  - ./bin/openstudio_meta  install_gems --export="/Users/alex/server-export"

