stages:
  - build
  - deploy

build:windows:
  stage: build
  tags:
    - windows
  script:
    - C:/Ruby22-x64/bin/ruby.exe ./bin/openstudio_meta install_gems --export="C:/openstudioServerExport" --ruby-lib-path="C:/openstudio/Ruby/" --verbose --debug

build:mac:
  stage: build
  tags:
    - mac
  script:
    - /Users/alex/.rvm/rubies/ruby-2.2.4/bin/ruby ./bin/openstudio_meta install_gems --export="/Users/alex/Desktop/server-export" --ruby-lib-path=/Applications/openstudio/Ruby/ --verbose --debug

deploy:windows:
  stage: deploy
  tags:
    - windows
  dependencies:
    - build:windows
  script:
    - cd C:/openstudioServerExport/
    - aws s3 cp ./ s3://openstudio-builds/CI/ --exclude "*" --include "OpenStudio-server-*-win32.tar.gz"

deploy:mac:
  stage: deploy
  tags:
    - mac
  dependencies:
    - build:mac
  script:
    - cd /Users/alex/Desktop/server-export/
    - aws s3 cp ./ s3://openstudio-builds/CI/ --exclude "*" --include "OpenStudio-server-*-darwin.tar.gz"

