AllCops:
  Exclude:
    - 'server/spec/files/**/*'
    - 'server/lib/delayed/heartbeat/**/*'
    - 'server/vendor/bundle/**/*'

inherit_from:
  - https://raw.githubusercontent.com/NREL/OpenStudio-resources/develop/styles/rubocop.yml
  - https://raw.githubusercontent.com/NREL/OpenStudio-resources/develop/styles/rubocop-rails.yml
