AllCops:
  Exclude:
    - 'server/spec/files/**/*'
    - 'server/lib/delayed/heartbeat/**/*'
    - 'server/vendor/bundle/**/*'
    - 'lib/update_license.rb'

inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop.yml
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop-rails.yml
