version: 1.0.{build}-{branch}

environment:
  USE_TESTING_TIMEOUTS: "true"
  OPENSTUDIO_VERSION: 2.6.2
  OPENSTUDIO_VERSION_SHA: 8c2673f388
  
  matrix:
    - RUBY_VERSION: "224-x64"

clone_folder: C:\projects\openstudio-server

install:
  - C:\projects\openstudio-server\ci\appveyor\setup.cmd

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - mongod.exe --version

test_script:
  - ps: C:\projects\openstudio-server\ci\appveyor\integration-test.ps1
  - cmd: C:\projects\openstudio-server\ci\appveyor\unit-test.cmd

on_success:
  - C:\projects\openstudio-server\ci\appveyor\build_release.cmd

on_failure:
  - C:\projects\openstudio-server\ci\appveyor\print_logs.cmd

artifacts:
  - path: /e/openstudio-server-build
  - name: ossBuild
