version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: "200-x64"

clone_folder: C:\projects\openstudio-server

install:
  - C:\projects\openstudio-server\ci\appveyor\setup.cmd

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - mongod.exe --version

test_script:
  - ps: C:\projects\openstudio-server\ci\appveyor\test.ps1

on_failure:
  - C:\projects\openstudio-server\ci\appveyor\print_logs.cmd

notifications:
  - provider: Slack
    auth_token:
      secure: 8Ge+Ia1v2AwaVl+/6ycJHBo0WHswdqY93sNDJIuqghBNjZFDdp+oXm3+wefe7aI0351laBCoPp9p4znFx1fOgEbfc4XvAaZgQYnsCuXCZk0=
    channel: server
    on_build_success: false
    on_build_failure: false