version: 1.0.{build}-{branch}

environment:
  USE_TESTING_TIMEOUTS: "true"
  OPENSTUDIO_VERSION: 2.9.0
  OPENSTUDIO_VERSION_SHA: 801faa459c
  OPENSTUDIO_VERSION_EXT:
  OPENSTUDIO_TEST_EXE: C:\projects\openstudio\bin\openstudio.exe

  
  matrix:
    - RUBY_VERSION: "224-x64"

clone_folder: C:\projects\openstudio-server

install:
  - C:\projects\openstudio-server\ci\appveyor\setup.cmd

build: off

before_test:
  - cmd: ruby -v
  - cmd: gem -v
  - cmd: bundle -v
  - cmd: mongod.exe --version

test_script:
  - ps: C:\projects\openstudio-server\ci\appveyor\integration-test.ps1
  - cmd: C:\projects\openstudio-server\ci\appveyor\unit-test.cmd

on_failure:
  - cmd: C:\projects\openstudio-server\ci\appveyor\print_logs.cmd
