# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '2'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  web:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    links:
      - db
      - rserve
    ports:
      - "8080:80"
    volumes:
      - osdata:/mnt/openstudio
  web-background:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    links:
      - db
      - rserve
    volumes:
      - osdata:/mnt/openstudio
    command: bin/delayed_job -i server --queues=analyses,background run
  worker:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    links:
      - web
      - db
      - rserve
    command: bin/delayed_job -i worker --queue=simulations run
  rserve:
    image: nrel/openstudio-rserve:latest
    build: ./docker/R
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    volumes:
      - osdata:/mnt/openstudio
volumes:
  osdata:
    external: true
