# Version used to deploy the latest version of the server from docker hub.

version: '3.4'
services:
  db:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
  queue:
      image: redis:4.0.6
      ports:
        - "6379:6379"
  web:
    image: nrel/openstudio-server:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
      - QUEUES=analysis_wrappers
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
    command: /usr/local/bin/start-server
  web-background:
    image: nrel/openstudio-server:latest
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
      - QUEUES=background,analyses
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - queue
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
    command: /usr/local/bin/start-web-background
  worker:
    image: nrel/openstudio-server:latest
    environment:
      - QUEUES=simulations
      - COUNT=1
    volumes:
      - /mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - rserve
    deploy:
      resources:
        reservations:
          cpus: "1"
    command: /usr/local/bin/start-workers
  rserve:
    image: nrel/openstudio-rserve:latest
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
volumes:
  osdata:
    external: true
networks:
  default:
    driver: overlay
