# Docker Compose creates multiple containers on a single machine.
# run `docker-compose up` to create and run/link the containers
version: '3'
services:
  db:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  queue:
    image: redis:4.0.6
    ports:
      - "6379:6379"
  web:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    depends_on:
      - db
      - queue
    ports:
      - "8080:80"
    volumes:
      - osdata:/mnt/openstudio
  web-background:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
      - QUEUES=background,analyses
    depends_on:
      - db
      - queue
      - web
    volumes:
      - osdata:/mnt/openstudio
    command: bundle exec rake environment resque:work
  worker:
    image: nrel/openstudio-server:latest
    build:
      context: .
      args:
        rails_env: docker
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
      - QUEUES=simulations
      - COUNT=1
    depends_on:
      - web
      - db
      - queue
      - rserve
    command: bundle exec rake environment resque:workers
  rserve:
    image: nrel/openstudio-rserve:latest
    build: ./docker/R
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
volumes:
  osdata:
    external: true
  dbdata:
    external: true
