version: '3.4'
services:
  db:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "${AWS_MONGO_CORES}"
  queue:
    image: redis:4.0.6
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
  web:
    image: nrel/openstudio-server:3-prerelease-rc2-2.8.1
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${AWS_OS_SERVER_NUMBER_OF_WORKERS}
      - MAX_REQUESTS=${AWS_MAX_REQUESTS}
      - MAX_POOL=${AWS_MAX_POOL}
      - QUEUES=analysis_wrappers
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - queue
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "${AWS_WEB_CORES}"
    command: /usr/local/bin/start-server
  web-background:
    image: nrel/openstudio-server:3-prerelease-rc2-2.8.1
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${AWS_OS_SERVER_NUMBER_OF_WORKERS}
      - QUEUES=background,analyses
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - web
      - queue
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
    command: /usr/local/bin/start-web-background
  worker:
    image: nrel/openstudio-server:3-prerelease-rc2-2.8.1
    environment:
      - QUEUES=simulations
      - COUNT=1
    volumes:
      - /mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - queue
      - rserve
    deploy:
      resources:
        reservations:
          cpus: "1"
    command: /usr/local/bin/start-workers
  rserve:
    image: nrel/openstudio-rserve:3-prerelease-rc2-2.8.1
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
  notebook:
    image: 127.0.0.1:5000/openstudio-jupyter
    ports:
      - "8888:8888"
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - queue
      - rserve  
volumes:
  osdata:
    external: true
  dbdata:
    external: true
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
