version: '3.4'
services:
  db:
    image: 127.0.0.1:5000/mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager
  queue:
    image: 127.0.0.1:5000/redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - node.role == manager
  web:
    image: 127.0.0.1:5000/openstudio-server
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=1
      - MAX_REQUESTS=10
      - MAX_POOL=10
      - QUEUES=analysis_wrappers
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - queue
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: /usr/local/bin/start-server
  web-background:
    image: 127.0.0.1:5000/openstudio-server
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=1
      - QUEUES=background,analyses
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
      - web
      - queue
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: /usr/local/bin/start-web-background
  worker:
    image: 127.0.0.1:5000/openstudio-server
    environment:
      - QUEUES=simulations
      - COUNT=1
    volumes:
      - /mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - queue
      - rserve
    command: /usr/local/bin/start-workers
  rserve:
    image: 127.0.0.1:5000/openstudio-rserve
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
  notebook:
    image: 127.0.0.1:5000/openstudio-jupyter
    ports:
      - "8888:8888"
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
      - queue
      - rserve  
volumes:
  osdata:
    external: true
  dbdata:
    external: true
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
