version: '3'
services:
  db:
    image: localhost:5000/mongo
    ports:
      - "27017:27017"
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
  web:
    image: localhost:5000/openstudio-server
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
  web-background:
    image: localhost:5000/openstudio-server
    environment:
      - OS_SERVER_NUMBER_OF_WORKERS=${OS_SERVER_NUMBER_OF_WORKERS}
    volumes:
      - osdata:/mnt/openstudio
    command: bin/delayed_job -i server --queues=analyses,background run
    depends_on:
      - db
      - web
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
  worker:
    image: localhost:5000/openstudio-server
    command: bin/delayed_job -i worker --queue=simulations run
    depends_on:
      - web
      - web-background
      - db
      - rserve
    deploy:
      resources:
        reservations:
          cpus: "0.99"
  rserve:
    image: localhost:5000/openstudio-rserve
    volumes:
      - osdata:/mnt/openstudio
    depends_on:
      - web
      - web-background
      - db
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          cpus: "1"
volumes:
  osdata:
    external: true
networks:
  default:
    driver: overlay
